# Dataset exploration
Available at the next link. We have to do some data preprocessing so it is legible by the models.

In [26]:
import pandas as pd
import os

In [27]:
#Getting the individuals
path = 'outputs/features'

def get_individuals():
    individuals = set()
    for filename in os.listdir(path):
        if '.out' in filename:
            file_path = os.path.join(path, filename)
            individuals.add(file_path.split('_')[0].split('/')[2])
    return list(individuals)

individuals = get_individuals()

In [28]:
#Getting the data from the .out files
features = ['count', 'hr', 'cosine', 'time', 'psg']
def data_(individual):
    df_list = []
    for filename in os.listdir(path):
        file_path = os.path.join(path, filename)
        if os.path.isfile(file_path) and individual in file_path:
            feature = file_path.split('_')[1]
            with open(file_path, 'r') as file:
                lines = file.readlines()
            data = []

            for line in lines:
                line = float(line[:-1])
                data.append(line)
            df = pd.DataFrame(data, columns = [feature])
            df_list.append(df)
    
    database = pd.concat(df_list, axis = 1)
    database = database.reindex(columns = features)

    return database

In [29]:
#Concatenate all individual dataframes
database_list = []
for i in get_individuals():
    database_list.append(data_(i))

df = pd.concat(database_list,keys = individuals)

In [30]:
#REM and NREM classification
df.loc[df['psg']!=5,['psg']] = 0
df.loc[df['psg']==5,['psg']] = 1
df

                 count        hr    cosine      time  psg
1449548 0    52.235491  0.614925 -0.258819  0.000000  0.0
        1    58.012114  0.608567 -0.260926  0.008333  0.0
        2    53.536372  0.617486 -0.263031  0.016667  0.0
        3    41.277177  0.609667 -0.265135  0.025000  0.0
        4    27.159358  0.606250 -0.267238  0.033333  0.0
...                ...       ...       ...       ...  ...
9618981 938   0.000000  0.092941 -0.740218  7.816667  0.0
        939   0.000000  0.085237 -0.738749  7.825000  0.0
        940   0.000000  0.083318 -0.737277  7.833333  0.0
        941   0.000000  0.084314 -0.735802  7.841667  0.0
        942   0.000000  0.085555 -0.734323  7.850000  0.0

[25481 rows x 5 columns]

In [31]:
#REM
df.loc[df['psg']==1, :]

                count        hr    cosine      time  psg
1449548 180  0.079658  0.479166 -0.608761  1.500000  1.0
        181  0.296176  0.443298 -0.610491  1.508333  1.0
        182  0.772338  0.417215 -0.612217  1.516667  1.0
        183  1.412611  0.401578 -0.613941  1.525000  1.0
        185  1.633345  0.381763 -0.617379  1.541667  1.0
...               ...       ...       ...       ...  ...
9618981 904  0.055518  1.207965 -0.788011  7.533333  1.0
        905  0.270369  1.193676 -0.786666  7.541667  1.0
        906  0.923429  1.171150 -0.785317  7.550000  1.0
        907  2.212038  1.162640 -0.783964  7.558333  1.0
        912  0.853598  1.149172 -0.777146  7.600000  1.0

[5540 rows x 5 columns]

In [32]:
#save csv
df.to_csv('data.csv')